### ISSUE TITLE
Missing starting gold when resetting ingame using -ng

### ISSUE THREAD

**Issue by Microhive** [dtchitt/wc3-risk-system#18]
It appears that resetting the game does give players their starting gold in the first turn. After the first turn, they get the expected income. 

Expected behaviour is that players get gold in their first turn in a -ng reset.

**Comment by dtchitt** [comment]
I just tested and it worked fine for me on latest main. Are you testing in promode or non promode?

**Comment by dtchitt** [comment]
I watched the video, I am going to assume its something to do with the pausing and unpausing of units. This is a new issue and not only did  you not get gold, the timer didnt reset. Id start by debugging the pausing and unpausing. I debug in wc3 by printing to screen.

**Comment by Microhive** [comment]
Issue is related to #8.

**Comment by Microhive** [comment]
Merged #17. That solves this problem.
